# Generated by Django 4.2.4 on 2023-09-14 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drywallinspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drywall_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='electricalinspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='finalinspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='foundationinspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundation_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='framinginspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framing_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='hvacinspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hvac_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='insulationinspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulation_inspection', to='client.clientprofile'),
        ),
        migrations.AlterField(
            model_name='plumbinginspection',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plumbing_inspection', to='client.clientprofile'),
        ),
    ]
