# Generated by Django 4.2.4 on 2023-09-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientprofile_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
