# Generated by Django 4.2.4 on 2023-09-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_clientprofile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='building_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
