# Generated by Django 4.2.4 on 2023-10-01 10:13

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientprofile_inspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundationinspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='foundationinspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='inspection_status',
            field=models.CharField(blank=True, default='Pending', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
