# Generated by Django 4.2.4 on 2023-10-01 11:02

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_foundationinspection_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drywallinspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='drywallinspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='electricalinspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='electricalinspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='finalinspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='finalinspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='framinginspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='framinginspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='hvacinspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='hvacinspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='insulationinspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='insulationinspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='plumbinginspection',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
        migrations.AddField(
            model_name='plumbinginspection',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.upload_to),
        ),
    ]
